version: "3.9"
services:
  client:
    build: .
    environment:
      - ROS_DOMAIN_ID=56
    command: "udp4 --port 8888 -v6"
    ports:
      - "8888:8888/udp"
      - "5000:5000"
    volumes:
      - ../:/app